version: "3.9"
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    restart: unless-stopped

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    restart: unless-stopped


  n8n:
    image: n8nio/n8n
    ports:
      - "50078:5678"       # Port değiştirildi
    environment:
      - GENERIC_TIMEZONE=Europe/Istanbul
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=db
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=anikutusu
      - DB_POSTGRESDB_USER=anikutusu
      - DB_POSTGRESDB_PASSWORD=anikutusu123
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=secret
    volumes:
      - n8n-data:/home/node/.n8n
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: anikutusu
      POSTGRES_PASSWORD: anikutusu123
      POSTGRES_DB: anikutusu
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db-init.sql:/docker-entrypoint-initdb.d/db-init.sql
    restart: unless-stopped

volumes:
  n8n-data:
  db-data:
