version: "3.8"

services:
  n8n:
    image: n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_CORS=*
      # İstersen daha güvenli:
      # - N8N_CORS=http://localhost:8080
    volumes:
      - ./n8n_data:/home/node/.n8n

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "8080:80"
