CREATE TABLE IF NOT EXISTS events (
  event_id VARCHAR(255) PRIMARY KEY,
  names VARCHAR(255) NOT NULL,
  mail VARCHAR(255) NOT NULL,
  date DATE NOT NULL,
  theme VARCHAR(50) NOT NULL,
  created_at TIMESTAMP DEFAULT NOW()
);
